# Generated by Django 3.0.7 on 2020-06-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_hash',
            field=models.CharField(max_length=200, null=True, verbose_name='Хэш изображения'),
        ),
    ]
